application: douiserver-test
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: web_gui.application
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
